name: asf-jupyter-notebook
channels:
  - conda-forge
dependencies:
#  - python=3.7
  - python=3.8
  - pip=20.1.1
  - numpy=1.19.1
  - matplotlib=3.3.2
  - gdal=3.1.3
  - pandas=1.1.3
  - rasterio=1.1.7
#  - scikit-fuzzy=0.4.2
  - scikit-fuzzy # added
  - pyproj=2.6.1.post1
  - nodejs
  - ipympl
  - geopandas # added
  - rioxarray # added
  - pip:
      - awscli==1.18.156
